/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jeff_ndk_MainActivity */

#ifndef _Included_org_jeff_ndk_MainActivity
#define _Included_org_jeff_ndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jeff_ndk_MainActivity
 * Method:    helloword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jeff_ndk_MainActivity_helloword
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
